
services:
  # 1. База данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: summarizer_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Очередь сообщений RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: summarizer_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"    
      - "15672:15672"  
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 8s
      timeout: 10s
      retries: 5

  # 3. Наш FastAPI веб-сервис
  web:
    build: .
    container_name: summarizer_web
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app  
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  #...Фоновый рабочий
  worker: 
    build: .
    container_name: summarizer_worker
    restart: always
    # Переопределяем команду запуска: вместо uvicorn запускаем наш скрипт!
    command: python worker.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  ollama:
    image: ollama/ollama:latest
    container_name: summarizer_ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  
volumes:
  postgres_data:
  ollama_data: 
